### ISSUE TITLE
JIT detection bug

### ISSUE THREAD

**Issue by Lotuashvili** [ErickTamayo/tailwindcss-named-groups#6]
I have an issue about JIT detection. It is reading only `group-hover` classes instead of my custom named classes.

I am using this for tooltips, which stopped working and I found out that it does generate classes depending on `group-hover` class only. Look at the screenshot, none of the `group-tooltip-hover` classes are declared in CSS, but there are ones which I used with `group-hover` prefix.

I have used `group-tooltip-hover:flex` and `group-tooltip-hover:opacity-40` and none of them are declared in CSS, but there's an `opacity-10` which was pulled from `group-hover` class.

<img width="833" alt="Screen Shot 2022-03-15 at 14 29 27" src="https://user-images.githubusercontent.com/6238393/158358959-300e72f7-86d6-4c4e-b259-fc3a2486427f.png">

<img width="762" alt="Screen Shot 2022-03-15 at 14 30 55" src="https://user-images.githubusercontent.com/6238393/158358971-e5f1c1bd-3692-400a-a1a7-ca96670c846e.png">

**Comment by onmax** [comment]
I just developed a new plugin very similar to this one that has all Tailwind 3 features.

Check it out here: https://github.com/onmax/tailwindcss-labeled-groups

**Comment by Lotuashvili** [comment]
Hey @onmax, I saw the demo from your Github and it does not work on v2. Maybe it's because of the coloring only, but can you make sure it works perfectly on v2? If so, I can switch to it, since there are no updates on this plugin.

**Comment by ErickTamayo** [comment]
@Lotuashvili please open an issue on the repo that has this issue. I'll close this as right now I have no time nor intention to update this plugin.
